export function isYouTubeVideoUrl(url: string) {
    const youtubeVideoUrlRegex = /^(https?:\/\/)?(www\.)?(youtube\.com\/(embed\/|v\/|watch\?v=)|youtu\.be\/)([a-zA-Z0-9_-]{8,})/;
    return youtubeVideoUrlRegex.test(url);
}

export const acceptedDurationList = [
    { value: "15", label: "15s" },
    { value: "30", label: "30s" },
    { value: "45", label: "45s" },
    { value: "60", label: "60s" },
    { value: "90", label: "90s" },
    { value: "120", label: "120s" },
];

export const acceptedLanguageList = [
    { value: "en", label: "english" },
    { value: "zh", label: "chinese" },
    { value: "de", label: "german" },
    { value: "es", label: "spanish" },
    { value: "ru", label: "russian" },
    { value: "ko", label: "korean" },
    { value: "fr", label: "french" },
    { value: "ja", label: "japanese" },
    { value: "pt", label: "portuguese" },
    { value: "tr", label: "turkish" },
    { value: "pl", label: "polish" },
    { value: "ca", label: "catalan" },
    { value: "nl", label: "dutch" },
    { value: "ar", label: "arabic" },
    { value: "sv", label: "swedish" },
    { value: "it", label: "italian" },
    { value: "id", label: "indonesian" },
    { value: "hi", label: "hindi" },
    { value: "fi", label: "finnish" },
    { value: "vi", label: "vietnamese" },
    { value: "he", label: "hebrew" },
    { value: "uk", label: "ukrainian" },
    { value: "el", label: "greek" },
    { value: "ms", label: "malay" },
    { value: "cs", label: "czech" },
    { value: "ro", label: "romanian" },
    { value: "da", label: "danish" },
    { value: "hu", label: "hungarian" },
    { value: "ta", label: "tamil" },
    { value: "no", label: "norwegian" },
    { value: "th", label: "thai" },
    { value: "ur", label: "urdu" },
    { value: "hr", label: "croatian" },
    { value: "bg", label: "bulgarian" },
    { value: "lt", label: "lithuanian" },
    { value: "la", label: "latin" },
    { value: "mi", label: "maori" },
    { value: "ml", label: "malayalam" },
    { value: "cy", label: "welsh" },
    { value: "sk", label: "slovak" },
    { value: "te", label: "telugu" },
    { value: "fa", label: "persian" },
    { value: "lv", label: "latvian" },
    { value: "bn", label: "bengali" },
    { value: "sr", label: "serbian" },
    { value: "az", label: "azerbaijani" },
    { value: "sl", label: "slovenian" },
    { value: "kn", label: "kannada" },
    { value: "et", label: "estonian" },
    { value: "mk", label: "macedonian" },
    { value: "br", label: "breton" },
    { value: "eu", label: "basque" },
    { value: "is", label: "icelandic" },
    { value: "hy", label: "armenian" },
    { value: "ne", label: "nepali" },
    { value: "mn", label: "mongolian" },
    { value: "bs", label: "bosnian" },
    { value: "kk", label: "kazakh" },
    { value: "sq", label: "albanian" },
    { value: "sw", label: "swahili" },
    { value: "gl", label: "galician" },
    { value: "mr", label: "marathi" },
    { value: "pa", label: "punjabi" },
    { value: "si", label: "sinhala" },
    { value: "km", label: "khmer" },
    { value: "sn", label: "shona" },
    { value: "yo", label: "yoruba" },
    { value: "so", label: "somali" },
    { value: "af", label: "afrikaans" },
    { value: "oc", label: "occitan" },
    { value: "ka", label: "georgian" },
    { value: "be", label: "belarusian" },
    { value: "tg", label: "tajik" },
    { value: "sd", label: "sindhi" },
    { value: "gu", label: "gujarati" },
    { value: "am", label: "amharic" },
    { value: "yi", label: "yiddish" },
    { value: "lo", label: "lao" },
    { value: "uz", label: "uzbek" },
    { value: "fo", label: "faroese" },
    { value: "ht", label: "haitian creole" },
    { value: "ps", label: "pashto" },
    { value: "tk", label: "turkmen" },
    { value: "nn", label: "nynorsk" },
    { value: "mt", label: "maltese" },
    { value: "sa", label: "sanskrit" },
    { value: "lb", label: "luxembourgish" },
    { value: "my", label: "myanmar" },
    { value: "bo", label: "tibetan" },
    { value: "tl", label: "tagalog" },
    { value: "mg", label: "malagasy" },
    { value: "as", label: "assamese" },
    { value: "tt", label: "tatar" },
    { value: "haw", label: "hawaiian" },
    { value: "ln", label: "lingala" },
    { value: "ha", label: "hausa" },
    { value: "ba", label: "bashkir" },
    { value: "jw", label: "javanese" },
    { value: "su", label: "sundanese" },
];
