export type SVGAttrib = React.SVGProps<SVGSVGElement>;
export * from "./BellIcon";
export * from "./ConfigIcon";
export * from "./EnvelopIcon";
export * from "./InfoIcon";
export * from './PersonDoneIcon';
export * from "./ProfileIcon";
export * from "./LockIcon";
export * from "./LogoutIcon";
export * from "./BillingIcon";
export * from "./Recording01Icon";
